import type { FullReportOutputs } from "@/lib/export";

export type HaloPushOutputKey =
  | "client_email"
  | "actions"
  | "risks"
  | "summary"
  | "status_report";

export function buildHaloNoteHtml(
  outputs: Partial<FullReportOutputs> & Record<string, unknown>,
  selectedOutputs: HaloPushOutputKey[],
  projectName?: string,
  brandName?: string | null,
): string {
  const footerBrand =
    typeof brandName === "string" && brandName.trim() ? brandName.trim() : "Handover";
  const date = new Date().toLocaleDateString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });

  const esc = (v: unknown) =>
    String(v ?? "")
      .replaceAll("&", "&amp;")
      .replaceAll("<", "&lt;")
      .replaceAll(">", "&gt;");

  let html = `
  <div style="font-family:sans-serif;font-size:13px;line-height:1.6;color:#1a1a1a;">
    <div style="background:#0f172a;color:white;padding:10px 16px;border-radius:4px;margin-bottom:16px;">
      <strong style="color:#38bdf8;">HANDOVER</strong>
      <span style="color:rgba(255,255,255,0.5);margin-left:12px;font-size:12px;">Generated ${esc(date)}</span>
      ${projectName ? `<span style="color:rgba(255,255,255,0.5);margin-left:12px;font-size:12px;">· ${esc(projectName)}</span>` : ""}
    </div>
  `;

  if (selectedOutputs.includes("summary")) {
    html += `
      <div style="margin-bottom:20px;">
        <div style="font-size:10px;font-weight:700;letter-spacing:0.1em;text-transform:uppercase;color:#888;margin-bottom:8px;">Summary</div>
        <p style="margin:0;">${esc(outputs.summary ?? "")}</p>
      </div>
    `;
  }

  if (selectedOutputs.includes("client_email")) {
    html += `
      <div style="margin-bottom:20px;padding:12px 16px;background:#f8fafc;border-left:3px solid #38bdf8;border-radius:3px;">
        <div style="font-size:10px;font-weight:700;letter-spacing:0.1em;text-transform:uppercase;color:#888;margin-bottom:8px;">Client Email Draft</div>
        <div style="white-space:pre-line;">${esc(outputs.client_email ?? "")}</div>
      </div>
    `;
  }

  if (selectedOutputs.includes("actions") && Array.isArray(outputs.actions)) {
    const rows = (outputs.actions as Array<Record<string, unknown>>)
      .map(
        (a) => `
      <tr>
        <td style="padding:6px 10px;border:1px solid #e2e8f0;">${esc(a.task ?? "")}</td>
        <td style="padding:6px 10px;border:1px solid #e2e8f0;">${esc(a.suggested_owner ?? "Unassigned")}</td>
        <td style="padding:6px 10px;border:1px solid #e2e8f0;">${esc(a.priority ?? "Medium")}</td>
      </tr>`,
      )
      .join("");
    html += `
      <div style="margin-bottom:20px;">
        <div style="font-size:10px;font-weight:700;letter-spacing:0.1em;text-transform:uppercase;color:#888;margin-bottom:8px;">Action Log</div>
        <table style="width:100%;border-collapse:collapse;font-size:12px;">
          <thead>
            <tr style="background:#f1f5f9;">
              <th style="padding:6px 10px;text-align:left;border:1px solid #e2e8f0;">Action</th>
              <th style="padding:6px 10px;text-align:left;border:1px solid #e2e8f0;width:120px;">Owner</th>
              <th style="padding:6px 10px;text-align:left;border:1px solid #e2e8f0;width:80px;">Priority</th>
            </tr>
          </thead>
          <tbody>${rows}</tbody>
        </table>
      </div>
    `;
  }

  if (selectedOutputs.includes("risks") && Array.isArray(outputs.risks)) {
    const rows = (outputs.risks as Array<Record<string, unknown>>)
      .map(
        (r) => `
      <div style="padding:8px 12px;border:1px solid #fee2e2;border-left:3px solid #ef4444;border-radius:3px;margin-bottom:6px;font-size:12px;">
        <strong>${esc(r.risk ?? "")}</strong><br>
        <span style="color:#666;">${esc(r.impact ?? "")}</span><br>
        <span style="color:#888;font-style:italic;">Mitigation: ${esc(r.mitigation ?? "")}</span>
      </div>`,
      )
      .join("");
    html += `
      <div style="margin-bottom:20px;">
        <div style="font-size:10px;font-weight:700;letter-spacing:0.1em;text-transform:uppercase;color:#888;margin-bottom:8px;">Risk Log</div>
        ${rows}
      </div>
    `;
  }

  if (selectedOutputs.includes("status_report")) {
    html += `
      <div style="margin-bottom:20px;">
        <div style="font-size:10px;font-weight:700;letter-spacing:0.1em;text-transform:uppercase;color:#888;margin-bottom:8px;">Status Report</div>
        <div style="white-space:pre-line;font-size:12px;">${esc(outputs.status_report ?? "")}</div>
      </div>
    `;
  }

  html += `
    <div style="margin-top:24px;padding-top:12px;border-top:1px solid #e2e8f0;font-size:11px;color:#aaa;">
      Generated by ${esc(footerBrand)} · gethandover.uk
    </div>
  </div>`;

  return html;
}
