import { MetadataRoute } from "next";
import { BLOG_POSTS } from "@/lib/blog-data";

const today = new Date();

export default function sitemap(): MetadataRoute.Sitemap {
  const staticRoutes: MetadataRoute.Sitemap = [
    {
      url: "https://gethandover.uk",
      lastModified: today,
      changeFrequency: "monthly" as const,
      priority: 1,
    },
    {
      url: "https://gethandover.uk/halopsa-reporting",
      lastModified: today,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: "https://gethandover.uk/integrations/halopsa",
      lastModified: today,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: "https://gethandover.uk/about",
      lastModified: today,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: "https://gethandover.uk/compare",
      lastModified: today,
      changeFrequency: "monthly" as const,
      priority: 0.85,
    },
    {
      url: "https://gethandover.uk/compare/handover-vs-manual-reporting",
      lastModified: today,
      changeFrequency: "monthly" as const,
      priority: 0.85,
    },
    {
      url: "https://gethandover.uk/compare/handover-vs-brightgauge",
      lastModified: today,
      changeFrequency: "monthly" as const,
      priority: 0.85,
    },
    {
      url: "https://gethandover.uk/compare/handover-vs-rewst",
      lastModified: today,
      changeFrequency: "monthly" as const,
      priority: 0.85,
    },
    {
      url: "https://gethandover.uk/compare/handover-vs-chatgpt",
      lastModified: new Date(),
      changeFrequency: "monthly" as const,
      priority: 0.85,
    },
    {
      url: "https://gethandover.uk/compare/handover-vs-connectwise-reports",
      lastModified: new Date(),
      changeFrequency: "monthly" as const,
      priority: 0.85,
    },
    {
      url: "https://gethandover.uk/compare/handover-vs-halopsa-reports",
      lastModified: new Date(),
      changeFrequency: "monthly" as const,
      priority: 0.85,
    },
    {
      url: "https://gethandover.uk/compare/handover-vs-mspbots",
      lastModified: new Date(),
      changeFrequency: "monthly" as const,
      priority: 0.85,
    },
    {
      url: "https://gethandover.uk/compare/handover-vs-n8n",
      lastModified: new Date(),
      changeFrequency: "monthly" as const,
      priority: 0.85,
    },
    {
      url: "https://gethandover.uk/msp-reporting-software",
      lastModified: new Date(),
      changeFrequency: "monthly" as const,
      priority: 0.95,
    },
    {
      url: "https://gethandover.uk/contact",
      lastModified: today,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: "https://gethandover.uk/contact/sales",
      lastModified: today,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: "https://gethandover.uk/demo",
      lastModified: today,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: "https://gethandover.uk/features",
      lastModified: today,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: "https://gethandover.uk/features/automated-reports",
      lastModified: today,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: "https://gethandover.uk/features/qbr-generator",
      lastModified: today,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: "https://gethandover.uk/features/scheduled-reports",
      lastModified: today,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: "https://gethandover.uk/features/ai-insights",
      lastModified: today,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: "https://gethandover.uk/features/health-dashboard",
      lastModified: today,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: "https://gethandover.uk/features/psa-integration",
      lastModified: today,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: "https://gethandover.uk/features/exports",
      lastModified: today,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: "https://gethandover.uk/features/psa-push",
      lastModified: today,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: "https://gethandover.uk/features/white-label",
      lastModified: today,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: "https://gethandover.uk/features/halopsa-reporting",
      lastModified: today,
      changeFrequency: "monthly" as const,
      priority: 0.85,
    },
    {
      url: "https://gethandover.uk/features/connectwise-reporting",
      lastModified: today,
      changeFrequency: "monthly" as const,
      priority: 0.85,
    },
    {
      url: "https://gethandover.uk/features/msp-client-reporting",
      lastModified: today,
      changeFrequency: "monthly" as const,
      priority: 0.95,
    },
    {
      url: "https://gethandover.uk/features/revenue-at-risk",
      lastModified: new Date(),
      changeFrequency: "weekly" as const,
      priority: 0.9,
    },
    {
      url: "https://gethandover.uk/features/churn-replay",
      lastModified: new Date(),
      changeFrequency: "weekly" as const,
      priority: 0.9,
    },
    {
      url: "https://gethandover.uk/features/client-intelligence",
      lastModified: new Date(),
      changeFrequency: "weekly" as const,
      priority: 0.9,
    },
    {
      url: "https://gethandover.uk/integrations",
      lastModified: today,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: "https://gethandover.uk/integrations/connectwise",
      lastModified: today,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: "https://gethandover.uk/integrations/csv",
      lastModified: today,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: "https://gethandover.uk/integrations/slack",
      lastModified: today,
      changeFrequency: "monthly" as const,
      priority: 0.6,
    },
    {
      url: "https://gethandover.uk/integrations/teams",
      lastModified: today,
      changeFrequency: "monthly" as const,
      priority: 0.6,
    },
    {
      url: "https://gethandover.uk/join",
      lastModified: today,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: "https://gethandover.uk/pricing",
      lastModified: today,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: "https://gethandover.uk/roadmap",
      lastModified: today,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: "https://gethandover.uk/solutions",
      lastModified: today,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: "https://gethandover.uk/solutions/account-managers",
      lastModified: today,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: "https://gethandover.uk/solutions/msp-directors",
      lastModified: today,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: "https://gethandover.uk/solutions/project-managers",
      lastModified: today,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: "https://gethandover.uk/solutions/service-desk-managers",
      lastModified: today,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: "https://gethandover.uk/solutions/weekly-client-reporting",
      lastModified: today,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: "https://gethandover.uk/solutions/qbr",
      lastModified: new Date(),
      changeFrequency: "monthly" as const,
      priority: 0.9,
    },
    {
      url: "https://gethandover.uk/solutions/client-intelligence",
      lastModified: new Date(),
      changeFrequency: "weekly" as const,
      priority: 0.95,
    },
    {
      url: "https://gethandover.uk/solutions/service-review",
      lastModified: new Date(),
      changeFrequency: "weekly" as const,
      priority: 0.9,
    },
    {
      url: "https://gethandover.uk/solutions/project-delivery",
      lastModified: today,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: "https://gethandover.uk/solutions/sla-reporting",
      lastModified: today,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: "https://gethandover.uk/solutions/halopsa",
      lastModified: today,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: "https://gethandover.uk/solutions/connectwise",
      lastModified: today,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: "https://gethandover.uk/partners",
      lastModified: today,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: "https://gethandover.uk/partners/halopsa",
      lastModified: today,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: "https://gethandover.uk/partners/connectwise",
      lastModified: today,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: "https://gethandover.uk/blog",
      lastModified: today,
      changeFrequency: "weekly" as const,
      priority: 0.8,
    },
    {
      url: "https://gethandover.uk/case-studies",
      lastModified: today,
      changeFrequency: "weekly" as const,
      priority: 0.7,
    },
    {
      url: "https://gethandover.uk/case-studies/msp-weekly-reporting",
      lastModified: today,
      changeFrequency: "weekly" as const,
      priority: 0.7,
    },
    {
      url: "https://gethandover.uk/security",
      lastModified: today,
      changeFrequency: "yearly" as const,
      priority: 0.5,
    },
    {
      url: "https://gethandover.uk/privacy",
      lastModified: today,
      changeFrequency: "yearly" as const,
      priority: 0.3,
    },
    {
      url: "https://gethandover.uk/terms",
      lastModified: today,
      changeFrequency: "yearly" as const,
      priority: 0.3,
    },
  ];

  const blogRoutes: MetadataRoute.Sitemap = [
    ...BLOG_POSTS.map((post) => ({
      url: `https://gethandover.uk${post.routePath}`,
      lastModified: new Date(post.dateISO),
      changeFrequency: "weekly" as const,
      priority: 0.7,
    })),
  ];

  return [...staticRoutes, ...blogRoutes];
}
