import type { Metadata } from "next";

import { LegalPageShell } from "@/components/legal-page-shell";

export const metadata: Metadata = {
  alternates: {
    canonical: "https://gethandover.uk/terms",
  },
};

export default function TermsPage() {
  return (
    <LegalPageShell title="Terms of Service">
      <p className="section-label">Last updated: March 2026</p>

      <section>
        <h2 className="text-lg font-semibold text-[var(--text-primary)]">Using Handover</h2>
        <p className="mt-2">
          Handover is a tool for generating project delivery outputs from notes and ticket data. You must not use
          Handover to process sensitive personal data, financial data, or data you do not have permission to process.
        </p>
      </section>

      <section>
        <h2 className="text-lg font-semibold text-[var(--text-primary)]">Your account</h2>
        <p className="mt-2">
          You are responsible for keeping your account credentials secure. You must not share your account with others.
        </p>
      </section>

      <section>
        <h2 className="text-lg font-semibold text-[var(--text-primary)]">Payments and refunds</h2>
        <p className="mt-2">
          Subscriptions are billed monthly or annually. You can cancel at any time and retain access until the end of
          your billing period. We do not offer refunds for partial periods.
        </p>
      </section>

      <section>
        <h2 className="text-lg font-semibold text-[var(--text-primary)]">Availability</h2>
        <p className="mt-2">
          We aim for high availability but do not guarantee uninterrupted service. We are not liable for losses caused
          by downtime or errors in generated outputs.
        </p>
      </section>

      <section>
        <h2 className="text-lg font-semibold text-[var(--text-primary)]">Generated content</h2>
        <p className="mt-2">
          Outputs generated by Handover are AI-generated and should be reviewed before sending. You are responsible for
          the content you send to clients.
        </p>
      </section>

      <section>
        <h2 className="text-lg font-semibold text-[var(--text-primary)]">Intellectual property</h2>
        <p className="mt-2">
          Handover and its content are owned by Handover. Your input data and generated outputs belong to you.
        </p>
      </section>

      <section>
        <h2 className="text-lg font-semibold text-[var(--text-primary)]">Contact</h2>
        <p className="mt-2">For any questions email hello@gethandover.uk</p>
      </section>
    </LegalPageShell>
  );
}
